version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: cufcai_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cufcai_learn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cufcai_pg_data:/var/lib/postgresql/data

volumes:
  cufcai_pg_data:
